spring:
    application:
        name: fiap-ddd-java-atm-infra
    datasource:
        url: jdbc:sqlite:fiapbank.db
        driver-class-name: org.sqlite.JDBC
    jpa:
        database-platform: org.hibernate.dialect.SQLiteDialect
        hibernate:
            ddl-auto: update # O Hibernate criará as tabelas automaticamente!
        show-sql: true     # Imprime os comandos SQL no console