<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>br.com.fiap.bank</groupId>
        <artifactId>fiap-ddd-java-atm</artifactId>
        <version>1.0.0</version>
    </parent>

    <!-- Nome identificador deste submódulo -->
    <artifactId>infrastructure</artifactId>

    <!-- Configura o empacotamento para este módulo -->
    <packaging>jar</packaging>

    <dependencies>
        <!-- Dependência do módulo 'domain' (apenas o código) -->
        <dependency>
            <groupId>br.com.fiap.bank</groupId>
            <artifactId>domain</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- Driver SQLite JDBC -->
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.45.1.0</version>
        </dependency>

        <!-- JUnit 5 para Testes Automatizados -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.10.2</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>